import type { PartnerLead } from "@/types/partner-leads";

export const DEFAULT_PARTNER_LEADS: PartnerLead[] = [
  {
    id: "lead-clinica-lumina",
    type: "clinica",
    companyName: "Lumina Glow Clinic",
    contactName: "Patrícia Azevedo",
    email: "contato@luminaglow.com.br",
    phone: "+55 (11) 3999-7788",
    location: "São Paulo • SP",
    services: [
      "Harmonização facial premium",
      "Dermaplaning + boosters personalizados",
      "Programas corporais completos",
    ],
    notes: "Busca vitrine digital e agendamento online em tempo real.",
    createdAt: "2025-01-12T14:05:00.000Z",
    updatedAt: "2025-01-12T14:05:00.000Z",
  },
  {
    id: "lead-pro-karol",
    type: "profissional",
    companyName: "Karol Amaral - Glow Expert",
    contactName: "Karol Amaral",
    email: "karol.glow@doctorq.com",
    phone: "+55 (21) 98888-1122",
    location: "Rio de Janeiro • RJ",
    services: ["Skincare personalizado", "Consultoria homecare", "Rotinas Glow Up"],
    notes: "Precisa de agenda inteligente com integração a redes sociais.",
    createdAt: "2025-02-02T09:32:00.000Z",
    updatedAt: "2025-02-05T11:10:00.000Z",
  },
  {
    id: "lead-fabricante-aurora",
    type: "fabricante",
    companyName: "Aurora Biotech Dermocosméticos",
    contactName: "Marcelo Tavares",
    email: "parcerias@aurorabiotech.com",
    phone: "+55 (31) 3222-7070",
    location: "Belo Horizonte • MG",
    website: "https://aurorabiotech.com",
    services: ["Dermocosméticos biomiméticos", "Protocolos exclusivos de cabine"],
    notes: "Interesse em co-branding com clínicas premium.",
    createdAt: "2025-02-14T16:21:00.000Z",
    updatedAt: "2025-02-18T10:45:00.000Z",
  },
  {
    id: "lead-fornecedor-dermalink",
    type: "fornecedor",
    companyName: "DermaLink Distribuidora",
    contactName: "Rodrigo Ramos",
    email: "rodrigo@dermalink.com.br",
    phone: "+55 (41) 3777-2233",
    location: "Curitiba • PR",
    services: ["Equipamentos estéticos high-end", "Treinamentos in company"],
    notes: "Quer integrar catálogo com estoque dinâmico e pedidos B2B.",
    createdAt: "2025-03-01T13:00:00.000Z",
    updatedAt: "2025-03-01T13:00:00.000Z",
  },
];
