import type { ProfessionalProduct } from "@/types/professional-products";

export const DEFAULT_PROFESSIONAL_PRODUCTS: ProfessionalProduct[] = [
  {
    id: "prd-lasersculpt-pro",
    name: "LaserSculpt Pro 4D",
    category: "Equipamentos",
    subCategory: "Laser fracionado híbrido",
    summary: "Plataforma híbrida para rejuvenescimento facial e contorno corporal com inteligência adaptativa.",
    description:
      "O LaserSculpt Pro 4D combina tecnologia de laser fracionado híbrido com inteligência adaptativa em tempo real. Ele ajusta parâmetros conforme a leitura da derme, oferecendo resultados mais previsíveis e tempo de recuperação reduzido. Ideal para clínicas que buscam diferenciação em rejuvenescimento, textura de pele e bioestimulação de colágeno.",
    heroImage: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=1200&h=800&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1618005198919-d3d4b5a92eee?w=1200&h=900&fit=crop",
      "https://images.unsplash.com/photo-1612810806695-30ba0b38fa37?w=1200&h=900&fit=crop",
      "https://images.unsplash.com/photo-1620912189860-07942c1a2cda?w=1200&h=900&fit=crop",
    ],
    badge: "Inovação 2025",
    innovationScore: 9.6,
    roiIndicator: "Retorno estimado em 7 meses",
    keyBenefits: [
      "Sistema híbrido (Er:YAG + Nd:YAG) com ajuste inteligente",
      "Mapeamento térmico em tempo real com 200 leituras por segundo",
      "Protocolos pré-programados para 14 indicações estéticas",
      "Interface intuitiva com recomendações baseadas em IA",
    ],
    useCases: [
      "Skin resurfacing com downtime de 48 horas",
      "Melasma resistente e discromias complexas",
      "Bioestimulação de colágeno de 4ª geração",
      "Contorno corporal focado em áreas delicadas",
    ],
    protocolIdeas: [
      "LaserSculpt + bioestimulador injetável (intervalo de 21 dias)",
      "Protocolo híbrido LaserSculpt Pro + Drug Delivery",
      "Roteiro premium pré-evento com 3 sessões",
    ],
    technicalSpecs: [
      { label: "Potência máxima", value: "80 W (Er:YAG) / 120 W (Nd:YAG)" },
      { label: "Modos de pulso", value: "Long Pulse, UltraPulse, A.I. Sync" },
      { label: "Sistema de resfriamento", value: "CryoSmart integrado até -20 ºC" },
      { label: "Interface", value: "Display 18\" multi-touch com assistente de voz" },
      { label: "Dimensões", value: "128 x 62 x 44 cm" },
      { label: "Energia", value: "220V • 50/60 Hz • 2.0 kVA" },
    ],
    regulatoryNotes: [
      "Registro ANVISA: 1234567890",
      "Certificação CE Medical Grade",
      "Compatível com auditoria de biossegurança ISO 13485",
    ],
    trendingTags: ["laser", "rejuvenescimento", "alta tecnologia", "colágeno"],
    suppliers: [
      {
        id: "sup-dermatech",
        name: "DermaTech Systems",
        logoUrl: "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=200&h=200&fit=crop",
        location: "São Paulo • SP",
        specialization: "Equipamentos avançados para clínicas premium",
        contactEmail: "consultoria@dermatech.com.br",
        contactPhone: "+55 (11) 4002-1234",
        whatsapp: "https://wa.me/551199998888",
        website: "https://dermatech.com.br",
        leadTime: "Entrega em até 18 dias úteis",
        availability: "Pronta entrega limitada • Implantação assistida",
        highlights: [
          "Treinamento imersivo de 3 dias incluso",
          "Atualizações de software por 24 meses",
          "Plano de manutenção preditiva",
        ],
        rating: 4.9,
        reviewsCount: 128,
      },
      {
        id: "sup-laserhub",
        name: "LaserHub Medical",
        logoUrl: "https://images.unsplash.com/photo-1618005198919-d3d4b5a92eee?w=200&h=200&fit=crop",
        location: "Curitiba • PR",
        specialization: "Integração de plataformas energéticas com analytics",
        contactEmail: "contato@laserhub.com",
        contactPhone: "+55 (41) 3131-0000",
        website: "https://laserhub.com",
        leadTime: "Locação operacional disponível",
        availability: "Modelo locação ou compra assistida",
        highlights: [
          "Dashboard com métricas de ROI",
          "Equipe clínica para onboarding",
          "Seguro contra downtime incluso",
        ],
        rating: 4.7,
        reviewsCount: 94,
      },
    ],
    resources: [
      { label: "Catálogo técnico PDF", url: "https://example.com/catalogo-lasersculpt.pdf" },
      { label: "Estudo clínico multicêntrico", url: "https://example.com/estudo-lasersculpt.pdf" },
    ],
  },
  {
    id: "prd-bioflux-serum",
    name: "BioFlux Serum Ultra",
    category: "Dermocosméticos",
    subCategory: "Biotecnologia regenerativa",
    summary: "Sérum biomimético com ação multifásica para pós-procedimentos intensivos.",
    description:
      "Formulação biomimética com matriz de polipeptídeos inteligentes, precursores de colágeno tipo III e nanoesferas de ácido hialurônico. Desenvolvido para acelerar a recuperação pós-peelings químicos, microagulhamento robótico e lasers ablativos. Possui efeito calmante imediato e proteção antioxidante 72h.",
    heroImage: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=1200&h=800&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?w=1200&h=900&fit=crop",
      "https://images.unsplash.com/photo-1600180758890-d2ed3f3f8375?w=1200&h=900&fit=crop",
    ],
    badge: "Best Seller Clínico",
    innovationScore: 8.9,
    roiIndicator: "Margem média de 410% por protocolo vendido",
    keyBenefits: [
      "Matriz biomimética com liberação escalonada (12h, 24h, 48h)",
      "Sistema Neuro-Calm para redução imediata de escala visual de dor",
      "Compatível com protocolos home care e cabine",
      "pH adaptativo conforme microbiota cutânea",
    ],
    useCases: [
      "Pós-laser fracionado ablativo e não-ablativo",
      "Pós-bioestimuladores injetáveis",
      "Reabilitação de barreira cutânea em peles sensibilizadas",
      "Tratamentos de hipercromia inflamatória",
    ],
    technicalSpecs: [
      { label: "Apresentação", value: "30 ml • Airless inteligente" },
      { label: "Ativos chave", value: "Tripeptídeos inteligentes, HA de 3 pesos, niacinamida quiral" },
      { label: "Livre de", value: "Parabenos, silicones voláteis, fragrâncias sintéticas" },
      { label: "Estudos clínicos", value: "Redução de downtime em 42% (n=64 pacientes)" },
    ],
    regulatoryNotes: [
      "Registro ANVISA #9876543210",
      "Cruelty free • Vegan • Dermatologicamente testado",
    ],
    trendingTags: ["pós-procedimento", "dermocosmético", "biomimético"],
    suppliers: [
      {
        id: "sup-dermaflux",
        name: "DermaFlux Labs",
        location: "São Paulo • SP",
        specialization: "Biotecnologia regenerativa para uso profissional",
        contactEmail: "suporte@dermafluxlabs.com",
        contactPhone: "+55 (11) 2666-1414",
        whatsapp: "https://wa.me/551198889999",
        website: "https://dermafluxlabs.com",
        leadTime: "Despacho em até 24h para capitais",
        availability: "Distribuição nacional • Kits profissionais e revenda",
        highlights: [
          "Programa de fidelidade com cashback em cursos",
          "Material de marketing co-branded",
          "Rotulagem personalizada para clínicas VIP",
        ],
        rating: 4.8,
        reviewsCount: 211,
      },
      {
        id: "sup-elitecare",
        name: "Elite Care Distribuidora",
        location: "Porto Alegre • RS",
        specialization: "Dermocosméticos avançados e linhas exclusivas europeias",
        contactEmail: "contato@elitecare.com.br",
        contactPhone: "+55 (51) 3090-5050",
        leadTime: "Entrega Sul/Sudeste em 48h",
        availability: "Pronta entrega • Assinatura mensal para clínicas",
        highlights: [
          "Consultoria de protocolos híbridos",
          "Incentivo fiscal para compras recorrentes",
          "Treinamentos mensais com especialistas convidados",
        ],
        rating: 4.6,
        reviewsCount: 97,
      },
    ],
  },
  {
    id: "prd-criopulse-smart",
    name: "CrioPulse Smart Sculpt",
    category: "Equipamentos",
    subCategory: "Criolipólise multiaplicadores",
    summary: "Plataforma de criolipólise com controle térmico inteligente e aplicadores adaptativos 360º.",
    description:
      "CrioPulse Smart Sculpt redefine a criolipólise combinando 6 aplicadores independentes com controle térmico ativo. Cada ciclo é monitorado a partir de sensores capacitivos, entregando tratamentos personalizados para adiposidade localizada com maior conforto e previsibilidade.",
    heroImage: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=1200&h=800&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1601335556426-6fe87f1b92ab?w=1200&h=900&fit=crop",
      "https://images.unsplash.com/photo-1612810805944-507b5cbded03?w=1200&h=900&fit=crop",
    ],
    badge: "Top Body Contour",
    innovationScore: 9.1,
    roiIndicator: "Recupera investimento em 5 meses (ticket médio R$ 1.800)",
    keyBenefits: [
      "Aplicadores com sistema de compressão pneumática dinâmica",
      "Monitoramento otimizador com IA para evitar cristalização dérmica",
      "Banco de protocolos com 38 combinações por biotipo",
      "Dashboard com indicadores financeiros e de ocupação",
    ],
    useCases: [
      "Adiposidade localizada resistente",
      "Pré-operatório de lipo HD",
      "Protocolo Crio + Radiofrequência sinérgica",
      "Programas corporais intensivos de 12 semanas",
    ],
    technicalSpecs: [
      { label: "Aplicadores", value: "6 aplicadores independentes com 360º active-cooling" },
      { label: "Faixa de temperatura", value: "De -12 ºC a 5 ºC com tolerância ±0,1 ºC" },
      { label: "Sensores", value: "12 sensores capacitivos + 6 térmicos por aplicador" },
      { label: "Consumo energético", value: "220V • 3.5 kVA" },
      { label: "Conectividade", value: "Wi-Fi • Dashboard cloud • Atualizações OTA" },
    ],
    regulatoryNotes: [
      "Registro ANVISA em andamento (protocolo 2025/88745)",
      "Homologação UL & CE",
    ],
    trendingTags: ["criolipólise", "body contour", "monitoramento inteligente"],
    suppliers: [
      {
        id: "sup-bodysculpt",
        name: "BodySculpt Medical Group",
        location: "Rio de Janeiro • RJ",
        specialization: "Equipamentos premium para contorno corporal",
        contactEmail: "expansao@bodysculptmedical.com",
        contactPhone: "+55 (21) 3777-9000",
        website: "https://bodysculptmedical.com",
        leadTime: "Entrega em 25 dias • Implantação full service",
        availability: "Compra assistida • Leasing com manutenção inclusa",
        highlights: [
          "Mentoria comercial para lançar programas corporais",
          "Seguro dedicado contra downtime com equipamento backup",
          "Integração com prontuário eletrônico e CRM",
        ],
        rating: 4.8,
        reviewsCount: 83,
      },
    ],
  },
  {
    id: "prd-vision-skin-analyzer",
    name: "VisionSkin Analyzer X",
    category: "Tecnologia",
    subCategory: "Análise dermato-digital 5D",
    summary: "Scanner facial multiespectral com relatórios em realidade aumentada para consultas memoráveis.",
    description:
      "VisionSkin Analyzer X utiliza 7 espectros de luz (incluindo infravermelho e UV profundo) para mapear 28 indicadores dérmicos. O diferencial está na camada de realidade aumentada que projeta o plano de tratamento e evolução dentro da própria cabine, potencializando a adesão e ticket médio.",
    heroImage: "https://images.unsplash.com/photo-1600181952120-1d4a9cb9a868?w=1200&h=800&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1526256262350-7da7584cf5eb?w=1200&h=900&fit=crop",
      "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=1200&h=900&fit=crop",
    ],
    badge: "Experiência Imersiva",
    innovationScore: 9.4,
    roiIndicator: "Aumento médio de 27% em conversão de planos premium",
    keyBenefits: [
      "Relatórios personalizados com identidade visual da clínica",
      "App companion para acompanhar evolução do paciente",
      "Biblioteca de comparativos com IA explicativa",
      "Integração com protocolos da clínica e vitrine digital",
    ],
    useCases: [
      "Consultas iniciais memoráveis",
      "Programas de skin journey com assinatura",
      "Cross-selling de protocolos corporativos",
      "Teleconsultas com suporte remoto augmentado",
    ],
    technicalSpecs: [
      { label: "Espectros", value: "Luz branca, polarizada, UV, UV profundo, IR, fluorescência, azul frio" },
      { label: "Resolução", value: "48 MP • 5 ângulos simultâneos" },
      { label: "Processamento", value: "Chip Neural NX-2 • 12 TOPS" },
      { label: "Relatórios", value: "PDF, 3D Viewer, AR overlay" },
      { label: "Integrações", value: "API aberta • Webhook • CRM principais" },
    ],
    trendingTags: ["diagnóstico", "realidade aumentada", "experiência do paciente"],
    suppliers: [
      {
        id: "sup-visionlabs",
        name: "VisionLabs Healthtech",
        location: "Belo Horizonte • MG",
        specialization: "Tecnologia imersiva para clínicas de estética e dermatologia",
        contactEmail: "contato@visionlabs.com",
        contactPhone: "+55 (31) 4009-7070",
        website: "https://visionlabs.com",
        leadTime: "Entrega nacional em 10 dias",
        availability: "Compra ou assinatura mensal com hardware incluso",
        highlights: [
          "Treinamento presencial + biblioteca de scripts de venda",
          "Suporte remoto 24/7 com SLA de 2 horas",
          "Programa de co-marketing para lançamento",
        ],
        rating: 4.9,
        reviewsCount: 152,
      },
      {
        id: "sup-sensia",
        name: "Sensia Analytics",
        location: "Lisboa • Portugal",
        specialization: "Analytics avançado para clínicas médico-estéticas",
        contactEmail: "hello@sensiaanalytics.com",
        website: "https://sensiaanalytics.com",
        leadTime: "Integração remota em até 5 dias",
        availability: "Licenciamento internacional • Hub de dados em território nacional",
        highlights: [
          "Migration de dados incluso",
          "Relatórios personalizados e preditivos",
          "Community global com benchmarks trimestrais",
        ],
        rating: 4.7,
        reviewsCount: 64,
      },
    ],
  },
  {
    id: "prd-gloss-aurora-lip",
    name: "Gloss Aurora Lip Therapy",
    category: "Dermocosméticos",
    subCategory: "Tratamento labial luminoso",
    summary: "Gloss tratamento com tecnologia prisma que realça o tom natural enquanto hidrata profundamente.",
    description:
      "Aurora Lip Therapy combina ácido hialurônico tri-vector, esqualano bioidêntico e pigmentos prismáticos inteligentes. A fórmula cria efeito volumizador imediato, suaviza linhas e mantém hidratação por 24h. Ideal para protocolos pós-preenchimento e manutenção de lábios saudáveis.",
    heroImage: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=1200&h=800&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1585386959984-a4155224a1ad?w=1200&h=900&fit=crop",
      "https://images.unsplash.com/photo-1620912189860-07942c1a2cda?w=1200&h=900&fit=crop",
    ],
    badge: "Viral TikTok",
    innovationScore: 8.4,
    roiIndicator: "Aumenta ticket médio em até 35% no checkout",
    keyBenefits: [
      "Efeito prisma autoajustável (sem cor artificial)",
      "Blend de ceramidas botanicals para barreira labial",
      "Aplicador sem toque para protocolos in-clinic",
    ],
    useCases: [
      "Pós-preenchimento labial para manutenção do volume",
      "Protocolos de dermopigmentação labial",
      "Kit home care de programas Glow Up",
    ],
    technicalSpecs: [
      { label: "Apresentação", value: "Ponta metálica 12 ml • Airless" },
      { label: "Ativos", value: "Ácido hialurônico tri-vector, esqualano, lipopéptidos" },
      { label: "Efeito", value: "Volumização óptica em 5 minutos" },
    ],
    trendingTags: ["lábios saudáveis", "gloss tratamento", "hidratação 24h"],
    suppliers: [
      {
        id: "sup-lumiskin",
        name: "LumiSkin Lab",
        location: "São Paulo • SP",
        specialization: "Dermocosméticos premium com efeito ótico inteligente",
        contactEmail: "contato@lumiskinlab.com",
        contactPhone: "+55 (11) 3555-1212",
        highlights: [
          "Display boutique para venda assistida",
          "Treinamento comercial para equipe de recepção",
          "Fórmula exclusiva com alta recompra (60 dias)",
        ],
        rating: 4.7,
        reviewsCount: 88,
      },
    ],
  },
  {
    id: "prd-dreamskin-sleepmask",
    name: "DreamSkin Sleep Mask",
    category: "Dermocosméticos",
    subCategory: "Máscara noturna reparadora",
    summary: "Máscara em gel com liberação cronoativa alinhada às fases do sono para pele radiante ao despertar.",
    description:
      "DreamSkin Sleep Mask sincroniza ativos com as fases REM e Deep do sono. Durante REM, libera peptídeos luminosos; em Deep, entra o blend de niacinamida encapsulada e antioxidantes de longa duração. Ainda vem com aroma calmante patenteado.",
    heroImage: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=1200&h=800&fit=crop",
    badge: "Favorito das celebridades",
    keyBenefits: [
      "Liberação inteligente sincronizada com REM/Deep",
      "Textura gel refrescante para todos os tipos de pele",
      "Resultados visíveis após a primeira noite",
    ],
    useCases: [
      "Peles estressadas por procedimentos intensivos",
      "Protocolos de preparação pré-eventos",
      "Rotina para viagem (jet lag recovery)",
    ],
    technicalSpecs: [
      { label: "Ativos", value: "Peptídeos glow, niacinamida encapsulada, extrato de camomila azul" },
      { label: "Apresentação", value: "60 ml • pote frost com espátula magnética" },
    ],
    trendingTags: ["sono reparador", "glow amanhecer", "cronocosmético"],
    suppliers: [
      {
        id: "sup-nightlabs",
        name: "NightLabs Beauty",
        location: "Curitiba • PR",
        specialization: "Cronocosméticos inteligentes e aromaterapia clínica",
        highlights: [
          "Workshop de sono e performance para clientes VIP",
          "Material de PDV com QR code para playlist relaxante",
          "Programa de assinatura para recorrência",
        ],
        rating: 4.9,
        reviewsCount: 57,
      },
    ],
  },
  {
    id: "prd-nebulite-hydra-tool",
    name: "Nebulite Hydra Tool",
    category: "Equipamentos",
    subCategory: "Infusor ultrafino portátil",
    summary: "Caneta nebulizadora portátil para finalização de protocolos faciais com ativos personalizados.",
    description:
      "Nebulite Hydra utiliza vibração ultrassônica de 120 kHz para fragmentar ativos em microgotículas que aderem melhor à pele. Ideal para finalizar procedimentos ou montar kits homecare luxuosos.",
    heroImage: "https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?w=1200&h=800&fit=crop",
    keyBenefits: [
      "Design portátil com base recarregável magnética",
      "Compatível com boosters e essências personalizadas",
      "Acompanha app para sugerir blends conforme clima",
    ],
    technicalSpecs: [
      { label: "Autonomia", value: "Até 50 aplicações por carga" },
      { label: "Reservatório", value: "6 ml com trava segura" },
      { label: "Peso", value: "110 g" },
    ],
    trendingTags: ["finalização", "homecare premium", "experiência sensorial"],
    suppliers: [
      {
        id: "sup-hydraluxe",
        name: "HydraLuxe Devices",
        location: "São Paulo • SP",
        specialization: "Dispositivos de acabamento para clínicas boutique",
        highlights: [
          "Personalização da cor e gravação a laser",
          "Programa de recompra de cápsulas e boosters",
          "Manual visual para equipe com protocolos express",
        ],
      },
    ],
  },
  {
    id: "prd-holo-facial-kit",
    name: "Holo Facial Kit",
    category: "Tecnologia",
    subCategory: "Kit holográfico de diagnóstico",
    summary: "Kit para consultoras e profissionais cria projeções holográficas da pele via app mobile.",
    description:
      "O Holo Facial Kit utiliza um projetor compacto com câmera macro para mostrar em tempo real a textura, poros e planos de tratamento diretamente no rosto da cliente, criando uma experiência imersiva.",
    heroImage: "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=1200&h=800&fit=crop",
    keyBenefits: [
      "Projeção holográfica 3D com recomendações interativas",
      "Integração com CRM DoctorQ para registrar evolução",
      "Gera PDFs imediatos com protocolos sugeridos",
    ],
    technicalSpecs: [
      { label: "Compatibilidade", value: "iOS / Android via app" },
      { label: "Conectividade", value: "Wi-Fi / Bluetooth" },
      { label: "Portabilidade", value: "Case rígido com powerbank incluso" },
    ],
    trendingTags: ["diagnóstico imersivo", "holografia", "wow effect"],
    suppliers: [
      {
        id: "sup-holoskin",
        name: "HoloSkin Labs",
        location: "Lisboa • Portugal",
        specialization: "Experiências imersivas para consultas upgrade",
        highlights: [
          "Onboarding remoto com tutoriais em AR",
          "Suporte multilíngue 24/7",
          "Biblioteca de roteiros de venda consultiva",
        ],
      },
    ],
  },
  {
    id: "prd-sculptwave-body-oil",
    name: "SculptWave Body Oil",
    category: "Dermocosméticos",
    subCategory: "Óleo corporal efeito warm-cold",
    summary: "Óleo corporal inteligente que alterna sensação térmica para ativar microcirculação e drenagem.",
    description:
      "SculptWave utiliza encapsulados sensoriais que liberam calor suave durante massagem e sensação refrescante após 5 minutos. Ideal para protocolos de drenagem e massagens modeladoras em casa.",
    heroImage: "https://images.unsplash.com/photo-1618151313441-b46babe3e31a?w=1200&h=800&fit=crop",
    keyBenefits: [
      "Sensação térmica alternada (warm-cold)",
      "Blend de óleos secos com rápida absorção",
      "Ótimo para massagem com roller ou gua-sha corporal",
    ],
    technicalSpecs: [
      { label: "Volume", value: "150 ml" },
      { label: "Aroma", value: "Cítrico floral com notas de âmbar" },
      { label: "Livre de", value: "Parabenos, silicone, corantes" },
    ],
    trendingTags: ["spa em casa", "drenagem", "sensação térmica"],
    suppliers: [
      {
        id: "sup-wavebeauty",
        name: "Wave Beauty",
        location: "Porto Alegre • RS",
        specialization: "Produtos corporais premium e acessórios",
        highlights: [
          "Combo com ventosas e rollers dourados",
          "Programa de assinatura para revenda em clínicas",
          "Treinamento para equipe comercial",
        ],
      },
    ],
  },
  {
    id: "prd-crystal-dew-mist",
    name: "Crystal Dew Mist",
    category: "Dermocosméticos",
    subCategory: "Bruma antioxidante",
    summary: "Bruma facial com cristais energizados e antioxidantes de liberação contínua para reforço diário.",
    description:
      "A Crystal Dew Mist combina cristais micronizados de quartzo rosa com vitamina C estável, niacinamida e probióticos. Cria um escudo antioxidante, reforça a barreira e potencializa o glow instantâneo. Ideal para finalizar protocolos e oferecer experiência sensorial durante o dia.",
    heroImage: "https://images.unsplash.com/photo-1597909208735-8a11355f7b98?w=1200&h=800&fit=crop",
    badge: "Edição limitada",
    keyBenefits: [
      "Escudo antioxidante por 8 horas",
      "Fragrância sutil com notas florais e cítricas",
      "Compatível com maquiagem e procedimentos pós-laser",
    ],
    technicalSpecs: [
      { label: "Apresentação", value: "Bruma 100 ml • frasco de vidro esmerilado" },
      { label: "Ativos", value: "Vitamina C estabilizada 5%, niacinamida, probióticos" },
    ],
    trendingTags: ["antioxidante", "glow diário", "quartzo rosa"],
    suppliers: [
      {
        id: "sup-crystalbeauty",
        name: "Crystal Beauty Lab",
        location: "São Paulo • SP",
        specialization: "Brumas sofisticadas e experiências aromáticas",
        highlights: [
          "Personalização com logotipo da clínica",
          "Vitrine ilustrada e materiais sensoriais",
          "Combo com roller e bolsa térmica",
        ],
        rating: 4.7,
        reviewsCount: 61,
      },
    ],
  },
  {
    id: "prd-biolift-eye-patch",
    name: "BioLift Eye Patch",
    category: "Consumíveis",
    subCategory: "Patches para área dos olhos",
    summary: "Patches biodegradáveis com biopeptídeos e cafeína nanoencapsulada para revitalizar a área dos olhos.",
    description:
      "BioLift Eye Patch é uma solução pronta para cabine e homecare. Patches biodegradáveis aderem confortavelmente e liberam biopeptídeos lifting, cafeína nanoencapsulada e extrato de romã. Resultados perceptíveis em 15 minutos.",
    heroImage: "https://images.unsplash.com/photo-1612810806563-4ff20c0d88b1?w=1200&h=800&fit=crop",
    keyBenefits: [
      "Redução de bolsas e olheiras em uma aplicação",
      "Material biodegradável com aderência perfeita",
      "Ideal para protocolos pré-evento",
    ],
    technicalSpecs: [
      { label: "Apresentação", value: "Caixa com 10 pares • dose única" },
      { label: "Tempo de ação", value: "15 a 20 minutos" },
      { label: "Indicação", value: "Uso cabine + homecare premium" },
    ],
    trendingTags: ["eye care", "anti-inchaço", "quick fix"],
    suppliers: [
      {
        id: "sup-oculare",
        name: "Oculare Pro Lab",
        location: "Rio de Janeiro • RJ",
        specialization: "Tratamentos para área dos olhos",
        highlights: [
          "Programa de assinatura mensal",
          "Kit demonstração com materiais de PDV",
          "Suporte em eventos corporativos de lançamento",
        ],
      },
    ],
  },
  {
    id: "prd-sonic-glow-brush",
    name: "Sonic Glow Brush",
    category: "Tecnologia",
    subCategory: "Escova facial sônica",
    summary: "Escova facial inteligente com sensores de pressão, vibração sônica e conexão via app.",
    description:
      "A Sonic Glow Brush utiliza vibração sônica ajustável em 5 níveis e sensores de pressão para evitar fricção excessiva. O app companion indica a rotina ideal e registra métricas semanais. Perfeito para kits homecare de clínicas que vendem protocolos de manutenção.",
    heroImage: "https://images.unsplash.com/photo-1613758947303-86487dfb39ab?w=1200&h=800&fit=crop",
    keyBenefits: [
      "Sensores de pressão com alerta vibratório",
      "Cerdas híbridas em silicone antimicrobiano",
      "App com rotina personalizada e desafios gamificados",
    ],
    technicalSpecs: [
      { label: "Autonomia", value: "Até 45 usos por carga" },
      { label: "Resistência", value: "IPX7 • uso no banho" },
      { label: "Conectividade", value: "Bluetooth + App iOS/Android" },
    ],
    trendingTags: ["skin tech", "homecare conectado", "gamificação"],
    suppliers: [
      {
        id: "sup-soniqcare",
        name: "SoniqCare Devices",
        location: "Florianópolis • SC",
        specialization: "Dispositivos inteligentes para rotinas de skincare",
        highlights: [
          "Dashboard com adesão dos pacientes",
          "Programa de treinamento e workshop",
          "Bundles com dermocosméticos parceiros",
        ],
      },
    ],
  },
];
