-- =============================================
-- DoctorQ - Seed 001: Fornecedores
-- =============================================
-- Descrição: Dados de exemplo de fornecedores
-- Data: 2025-01-23
-- =============================================

-- Limpar dados existentes (se necessário)
-- TRUNCATE TABLE tb_fornecedores CASCADE;

-- Inserir fornecedores de exemplo
INSERT INTO tb_fornecedores (
    id_fornecedor,
    nm_empresa,
    ds_razao_social,
    nr_cnpj,
    nr_inscricao_estadual,
    ds_descricao,
    ds_site,
    ds_email,
    nr_telefone,
    nr_whatsapp,
    ds_endereco,
    nr_numero,
    ds_complemento,
    nm_bairro,
    nm_cidade,
    nm_estado,
    nr_cep,
    ds_categorias_produtos,
    nr_tempo_entrega_dias,
    vl_frete_minimo,
    vl_pedido_minimo,
    ds_logo_url,
    st_ativo,
    st_verificado,
    nr_avaliacao_media,
    nr_total_avaliacoes
) VALUES
    (
        gen_random_uuid(),
        'Beleza Premium Distribuidora',
        'Beleza Premium Distribuidora de Cosméticos Ltda',
        '12.345.678/0001-90',
        '123.456.789.012',
        'Distribuidora especializada em produtos premium para clínicas de estética. Trabalhamos com as melhores marcas do mercado nacional e internacional.',
        'https://belezapremium.com.br',
        'vendas@belezapremium.com.br',
        '(11) 3456-7890',
        '(11) 98765-4321',
        'Rua das Flores',
        '1234',
        'Galpão 5',
        'Vila Mariana',
        'São Paulo',
        'SP',
        '04567-890',
        ARRAY['Cuidados Faciais', 'Cuidados Corporais', 'Maquiagem'],
        3,
        25.00,
        200.00,
        'https://images.unsplash.com/photo-1556228578-0d85b1a4d571',
        true,
        true,
        4.8,
        127
    ),
    (
        gen_random_uuid(),
        'Estética Professional Supply',
        'Estética Professional Supply Ltda ME',
        '98.765.432/0001-10',
        '987.654.321.098',
        'Fornecedor de equipamentos profissionais para estética. Representante oficial das principais marcas de aparelhos de radiofrequência, criolipólise e laser.',
        'https://esteticasupply.com.br',
        'contato@esteticasupply.com.br',
        '(11) 2345-6789',
        '(11) 97654-3210',
        'Av. Paulista',
        '2500',
        'Conjunto 1001',
        'Bela Vista',
        'São Paulo',
        'SP',
        '01310-300',
        ARRAY['Equipamentos'],
        7,
        50.00,
        1000.00,
        'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f',
        true,
        true,
        4.9,
        89
    ),
    (
        gen_random_uuid(),
        'Bio Natural Cosméticos',
        'Bio Natural Cosméticos Orgânicos S.A.',
        '11.222.333/0001-44',
        '112.223.334.445',
        'Linha completa de cosméticos naturais e orgânicos. Produtos veganos, cruelty-free e com certificação orgânica. Perfeito para clínicas que buscam alternativas sustentáveis.',
        'https://bionaturalcosmeticos.com.br',
        'comercial@bionaturalcosmeticos.com.br',
        '(21) 3344-5566',
        '(21) 99876-5432',
        'Rua Visconde de Pirajá',
        '550',
        'Loja 2',
        'Ipanema',
        'Rio de Janeiro',
        'RJ',
        '22410-002',
        ARRAY['Cuidados Faciais', 'Cuidados Corporais', 'Cuidados Capilares'],
        5,
        30.00,
        300.00,
        'https://images.unsplash.com/photo-1596755094514-f87e34085b2c',
        true,
        true,
        4.7,
        156
    ),
    (
        gen_random_uuid(),
        'Derma Science Brasil',
        'Derma Science Brasil Produtos Dermatológicos Ltda',
        '33.444.555/0001-66',
        '334.445.556.667',
        'Importadora e distribuidora de dermocosméticos de alta performance. Produtos de uso profissional com resultados comprovados clinicamente.',
        'https://dermasciencebrasil.com',
        'vendas@dermasciencebrasil.com',
        '(11) 4567-8901',
        '(11) 96543-2109',
        'Rua dos Três Irmãos',
        '789',
        NULL,
        'Vila Progredior',
        'São Paulo',
        'SP',
        '05615-040',
        ARRAY['Cuidados Faciais', 'Higiene'],
        4,
        20.00,
        250.00,
        'https://images.unsplash.com/photo-1556229010-6c3f2c9ca5f8',
        true,
        false,
        4.5,
        67
    ),
    (
        gen_random_uuid(),
        'Spa & Wellness Supply',
        'Spa & Wellness Supply Comercial Ltda',
        '44.555.666/0001-77',
        '445.556.667.778',
        'Tudo para seu spa e clínica de estética. Desde produtos de linha até mobiliário especializado. Atendemos todo o Brasil.',
        'https://spawellnesssupply.com.br',
        'atendimento@spawellnesssupply.com.br',
        '(11) 5678-9012',
        '(11) 95432-1098',
        'Av. Brigadeiro Faria Lima',
        '3500',
        'Sala 201',
        'Itaim Bibi',
        'São Paulo',
        'SP',
        '04538-133',
        ARRAY['Cuidados Faciais', 'Cuidados Corporais', 'Equipamentos', 'Higiene'],
        5,
        35.00,
        400.00,
        'https://images.unsplash.com/photo-1560750588-73207b1ef5b8',
        true,
        true,
        4.6,
        203
    ),
    (
        gen_random_uuid(),
        'MakeUp Pro Studio',
        'MakeUp Pro Studio Comércio de Cosméticos Ltda',
        '55.666.777/0001-88',
        '556.667.778.889',
        'Distribuidora especializada em maquiagem profissional. Marcas exclusivas para maquiadores e clínicas de estética que oferecem serviços de make.',
        'https://makeupprostudio.com.br',
        'vendas@makeupprostudio.com.br',
        '(11) 6789-0123',
        '(11) 94321-0987',
        'Rua Oscar Freire',
        '1500',
        'Loja 15',
        'Jardim Paulista',
        'São Paulo',
        'SP',
        '01426-001',
        ARRAY['Maquiagem'],
        3,
        25.00,
        200.00,
        'https://images.unsplash.com/photo-1512496015851-a90fb38ba796',
        true,
        true,
        4.9,
        341
    ),
    (
        gen_random_uuid(),
        'Hair Care Professional',
        'Hair Care Professional Distribuidora ME',
        '66.777.888/0001-99',
        '667.778.889.990',
        'Especialistas em tratamentos capilares profissionais. Produtos para reconstrução, hidratação e coloração de cabelos.',
        'https://haircarepro.com.br',
        'comercial@haircarepro.com.br',
        '(11) 7890-1234',
        '(11) 93210-9876',
        'Rua Augusta',
        '2690',
        'Conjunto 802',
        'Cerqueira César',
        'São Paulo',
        'SP',
        '01413-000',
        ARRAY['Cuidados Capilares'],
        4,
        30.00,
        250.00,
        'https://images.unsplash.com/photo-1522338242992-e1a54906a8da',
        true,
        true,
        4.7,
        112
    ),
    (
        gen_random_uuid(),
        'Tech Estética Equipamentos',
        'Tech Estética Equipamentos Hospitalares Ltda',
        '77.888.999/0001-00',
        '778.889.990.001',
        'Importação e venda de equipamentos de última geração para tratamentos estéticos. Assistência técnica especializada em todo território nacional.',
        'https://techestetica.com.br',
        'vendas@techestetica.com.br',
        '(11) 8901-2345',
        '(11) 92109-8765',
        'Av. Rebouças',
        '3970',
        'Bloco A',
        'Pinheiros',
        'São Paulo',
        'SP',
        '05401-450',
        ARRAY['Equipamentos'],
        10,
        100.00,
        5000.00,
        'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158',
        true,
        true,
        4.8,
        54
    );

-- Atualizar sequências e contadores
SELECT setval(pg_get_serial_sequence('tb_fornecedores', 'id_fornecedor'),
    (SELECT MAX(id_fornecedor::text)::int FROM tb_fornecedores WHERE id_fornecedor::text ~ '^[0-9]+$'),
    true) WHERE EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='tb_fornecedores' AND column_name='id_fornecedor' AND data_type='integer');

-- Verificar inserção
SELECT
    nm_empresa,
    nm_cidade,
    st_verificado,
    nr_avaliacao_media,
    nr_total_avaliacoes
FROM tb_fornecedores
ORDER BY nr_avaliacao_media DESC;

-- =============================================
-- FIM DO SEED
-- =============================================
