-- Migration: Seed de Eventos
-- Data: 2025-01-14
-- Descrição: Adiciona eventos de exemplo (webinars, workshops, congressos, imersões)

-- Inserir eventos de exemplo
INSERT INTO tb_universidade_eventos (
    id_evento,
    titulo,
    descricao,
    tipo,
    dt_inicio,
    dt_fim,
    duracao_horas,
    instrutor_nome,
    preco,
    preco_assinante,
    max_participantes,
    total_inscritos,
    stream_url,
    replay_url,
    fg_chat_habilitado,
    fg_metaverso_habilitado,
    metaverso_room_id,
    certificado_horas,
    thumbnail_url,
    status,
    tags,
    dt_criacao
) VALUES
-- Webinar 1 (Ao vivo em breve)
(
    gen_random_uuid(),
    'Toxina Botulínica: Novos Protocolos 2025',
    'Webinar ao vivo com demonstração prática dos novos protocolos de aplicação de toxina botulínica aprovados pela ANVISA. Discussão de casos clínicos e manejo de complicações.',
    'webinar',
    '2025-01-20 19:00:00',
    '2025-01-20 21:00:00',
    2,
    'Dra. Ana Costa',
    49.90,
    0.00,
    500,
    234,
    'https://meet.doctorq.app/webinar-toxina-2025',
    NULL,
    true,
    false,
    NULL,
    2,
    'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800',
    'agendado',
    ARRAY['toxina', 'injetaveis', 'protocolos', 'anvisa'],
    now()
),

-- Workshop 1 (Agendado)
(
    gen_random_uuid(),
    'Workshop Prático: MD Codes Avançado',
    'Workshop intensivo de 2 dias com prática em modelos anatômicos. Aprenda as técnicas avançadas de MD Codes para harmonização facial natural. Inclui kit de materiais.',
    'workshop',
    '2025-02-15 09:00:00',
    '2025-02-16 18:00:00',
    16,
    'Dr. João Silva',
    1990.00,
    1490.00,
    30,
    18,
    NULL,
    NULL,
    false,
    false,
    NULL,
    16,
    'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=800',
    'agendado',
    ARRAY['preenchedores', 'md-codes', 'harmonizacao', 'pratica'],
    now()
),

-- Masterclass 1 (Finalizada - Replay disponível)
(
    gen_random_uuid(),
    'Masterclass: Marketing Digital para Clínicas de Estética',
    'Estratégias comprovadas de marketing digital para aumentar sua base de clientes. Análise de cases de sucesso e ferramentas práticas para implementar hoje.',
    'masterclass',
    '2025-01-10 20:00:00',
    '2025-01-10 22:00:00',
    2,
    'Rafael Oliveira',
    0.00,
    0.00,
    NULL,
    872,
    NULL,
    'https://youtube.com/watch?v=exemplo-marketing-digital',
    false,
    false,
    NULL,
    0,
    'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800',
    'finalizado',
    ARRAY['marketing', 'digital', 'vendas', 'estrategia'],
    now()
),

-- Congresso (Agendado)
(
    gen_random_uuid(),
    'Congresso Internacional de Estética Avançada 2025',
    'Maior evento de estética do Brasil! 3 dias com mais de 50 palestrantes nacionais e internacionais. Networking, feira de tecnologias e certificação internacional.',
    'congresso',
    '2025-06-10 08:00:00',
    '2025-06-12 20:00:00',
    30,
    'Comitê Científico DoctorQ',
    2990.00,
    1990.00,
    1000,
    456,
    'https://meet.doctorq.app/congresso-2025',
    NULL,
    true,
    true,
    'doctorq-congress-2025',
    30,
    'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800',
    'agendado',
    ARRAY['congresso', 'internacional', 'networking', 'certificacao'],
    now()
),

-- Imersão 1 (Agendado)
(
    gen_random_uuid(),
    'Imersão: Peelings Químicos - Do Básico ao Avançado',
    'Imersão completa de 1 semana sobre peelings químicos. Teoria, prática supervisionada em pacientes reais, protocolos de segurança e manejo de complicações. Vagas limitadas.',
    'imersao',
    '2025-03-03 08:00:00',
    '2025-03-07 18:00:00',
    40,
    'Dra. Maria Santos',
    4990.00,
    3990.00,
    15,
    12,
    NULL,
    NULL,
    false,
    false,
    NULL,
    40,
    'https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?w=800',
    'agendado',
    ARRAY['peelings', 'quimicos', 'pratica', 'imersao'],
    now()
),

-- Webinar 2 (Finalizado - Replay)
(
    gen_random_uuid(),
    'Webinar: Lasers em Estética - Tecnologias 2025',
    'Novidades em tecnologia laser para rejuvenescimento, tratamento de manchas e cicatrizes. Comparativo entre diferentes plataformas e análise de custo-benefício.',
    'webinar',
    '2025-01-05 19:00:00',
    '2025-01-05 21:00:00',
    2,
    'Dr. Carlos Mendes',
    39.90,
    0.00,
    500,
    412,
    NULL,
    'https://youtube.com/watch?v=exemplo-lasers-2025',
    false,
    false,
    NULL,
    2,
    'https://images.unsplash.com/photo-1581594693702-fbdc51b2763b?w=800',
    'finalizado',
    ARRAY['laser', 'tecnologia', 'rejuvenescimento', 'equipamentos'],
    now()
),

-- Workshop 2 (Agendado)
(
    gen_random_uuid(),
    'Workshop: Gestão Financeira para Clínicas',
    'Workshop de 1 dia sobre gestão financeira específica para clínicas de estética. Fluxo de caixa, precificação, indicadores de performance e planejamento tributário.',
    'workshop',
    '2025-02-28 09:00:00',
    '2025-02-28 17:00:00',
    8,
    'Rafael Oliveira',
    490.00,
    290.00,
    50,
    32,
    NULL,
    NULL,
    false,
    false,
    NULL,
    8,
    'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=800',
    'agendado',
    ARRAY['financeiro', 'gestao', 'negocios', 'planejamento'],
    now()
),

-- Masterclass 2 (Agendado)
(
    gen_random_uuid(),
    'Masterclass: Fios de PDO - Técnicas e Indicações',
    'Masterclass gratuita sobre fios de PDO. Anatomia aplicada, técnicas de aplicação, indicações e contraindicações. Tire suas dúvidas ao vivo com especialista.',
    'masterclass',
    '2025-01-25 20:00:00',
    '2025-01-25 21:30:00',
    1,
    'Dra. Paula Ribeiro',
    0.00,
    0.00,
    NULL,
    89,
    'https://meet.doctorq.app/live-fios-pdo',
    NULL,
    true,
    false,
    NULL,
    0,
    'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=800',
    'agendado',
    ARRAY['fios', 'pdo', 'lifting', 'tecnicas'],
    now()
);

-- Verificação
SELECT
    COUNT(*) as total_eventos,
    COUNT(*) FILTER (WHERE status = 'agendado') as agendados,
    COUNT(*) FILTER (WHERE status = 'realizado') as realizados,
    COUNT(*) FILTER (WHERE tipo = 'webinar') as webinars,
    COUNT(*) FILTER (WHERE tipo = 'workshop') as workshops,
    COUNT(*) FILTER (WHERE tipo = 'live') as lives,
    COUNT(*) FILTER (WHERE tipo = 'congresso') as congressos,
    COUNT(*) FILTER (WHERE tipo = 'imersao') as imersoes
FROM tb_universidade_eventos;
